"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-06^9lqbw6fy0uls4%$b=x2s!^a_pyshm%o)s+vtlrc9-l=gi%9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'userprofile',
]

# Jazzmin Admin Configuration (optional - can be in settings.py)
JAZZMIN_SETTINGS = {
    "site_title": "Profile Admin",
    "site_header": "Profile Administration",
    "site_brand": "Zillul Karim",
    "show_sidebar": True,
    "site_logo": None,
    "login_logo": None,
    "copyright": "Zillul Karim",
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    'hide_models': ['auth.group', 'auth.user','userprofile.Experience'],
    "related_modal_active": True,
    'order_with_respect_to': [
        'userprofile', 
        # Models
        'userprofile.Profile',
        'userprofile.HomepageSlide',
        'userprofile.Journey',
        'userprofile.Achievement',
        'userprofile.CurrentRole',
        'userprofile.Education',
        'userprofile.AcademicThesis',
        'userprofile.Collaboration',
        'userprofile.Publication',
        'userprofile.Service',
        'userprofile.BlogPost',
        'userprofile.Contact',
        'userprofile.GalleryImage',
        'userprofile.Video',
    ],
    "icons": {
        # User Profile Models
        "userprofile.profile": "fas fa-user",
        "userprofile.journey": "fas fa-route",
        "userprofile.currentrole": "fas fa-briefcase",
        "userprofile.education": "fas fa-graduation-cap",
        "userprofile.academicthesis": "fas fa-file-alt",
        "userprofile.achievement": "fas fa-trophy",
        "userprofile.collaboration": "fas fa-handshake",
        "userprofile.publication": "fas fa-book",  # or "fas fa-newspaper"
        "userprofile.service": "fas fa-hands-helping",
        "userprofile.blogpost": "fas fa-blog",
        "userprofile.homepageslide": "fas fa-images",
        "userprofile.contact": "fas fa-envelope",
        "userprofile.galleryimage": "fas fa-image",
        "userprofile.video": "fas fa-video",
    }
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-primary",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Static files (CSS, JavaScript, etc.)
STATIC_URL = '/static/'

# Folders where you store static files (in development)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  

# Folder where static files will be collected (by collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CKEditor settings 
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'height': 300,
        'width': '100%',
    },
}
