# Generated by Django 5.2.4 on 2025-07-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_color', models.CharField(default='text-blue-700', max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('duration_color', models.CharField(default='text-blue-800', max_length=20)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Visit Site →', max_length=100)),
                ('button_color', models.CharField(default='bg-blue-800', max_length=20)),
                ('button_link', models.URLField(blank=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_roles', to='userprofile.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Journey', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='journey/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
        ),
    ]
