# Generated by Django 5.2.4 on 2025-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_galleryimage_currentrole_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentrole',
            name='image',
            field=models.ImageField(default='', upload_to='currentrole/'),
            preserve_default=False,
        ),
    ]
