# Generated by Django 5.2.4 on 2025-07-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_currentrole_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentrole',
            name='image',
        ),
    ]
