# Generated by Django 5.2.4 on 2025-07-08 18:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_currentrole_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrole',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
