# Generated by Django 5.2.4 on 2025-07-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('thesis_link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to='userprofile.profile')),
            ],
            options={
                'verbose_name_plural': 'Academic Theses',
                'ordering': ['order'],
            },
        ),
    ]
