# Generated by Django 5.2.4 on 2025-07-10 06:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_academicthesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicthesis',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
