# Generated by Django 5.2.4 on 2025-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_academicthesis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrole',
            name='button_color',
            field=models.CharField(default='blue-800', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentrole',
            name='company_color',
            field=models.CharField(default='blue-700', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentrole',
            name='duration_color',
            field=models.CharField(default='blue-800', max_length=20),
        ),
    ]
