# Generated by Django 5.2.4 on 2025-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_currentrole_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image specifically for the About section', null=True, upload_to='profile/about/'),
        ),
    ]
